export const seedData = {
  users: {
    _model: "User",
    moritz: {
      firstName: "Moritz",
      lastName: "Hutzler",
      email: "moritz@diehutzlers.de",
      password: "1",
      isAdmin: true,
    },
    jannis: {
      firstName: "Jannis",
      lastName: "Hutzler",
      email: "jannis@diehutzlers.de",
      password: "1",
    },
  },
  placemarks: {
    _model: "Placemark",
    steinerneBruecke: {
      title: "Steinerne Brücke",
      category: "Sightseeing",
      description: "Mittelalterliche Steinbrücke aus dem 12. Jahrhundert, UNESCO-Weltkulturerbe",
      latitude: 49.0225,
      longitude: 12.0969,
      userid: "->users.moritz",
      img: "https://images.unsplash.com/photo-1666293438241-9f9b3654f118?q=80&w=774&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    dom: {
      title: "Regensburger Dom",
      category: "Sightseeing",
      description: "Gotische Kathedrale St. Peter, Wahrzeichen der Stadt",
      latitude: 49.0192,
      longitude: 12.0975,
      userid: "->users.moritz",
      img: "https://images.unsplash.com/photo-1659100826967-5616a3b1501e?q=80&w=940&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    wurstkuchl: {
      title: "Historische Wurstkuchl",
      category: "Restaurants",
      description: "Älteste Bratwurstküche der Welt, seit 1146",
      latitude: 49.0224,
      longitude: 12.0965,
      userid: "->users.moritz",
      img: "https://images.unsplash.com/photo-1724078770616-2f8e19d75761?q=80&w=872&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    kneitinger: {
      title: "Kneitinger Keller",
      category: "Bars",
      description: "Traditioneller Biergarten mit Hausbrauerei",
      latitude: 49.0180,
      longitude: 12.0920,
      userid: "->users.jannis",
      img: "https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=1000",
    },
    scala: {
      title: "Scala Club",
      category: "Clubs",
      description: "Beliebter Nachtclub im Herzen von Regensburg",
      latitude: 49.0150,
      longitude: 12.0950,
      userid: "->users.jannis",
      img: "https://imageflow.rausgegangen.de/url/https%3A//s3.eu-central-1.amazonaws.com/rausgegangen/TPVOzMuRautpFSBN5wuQ_aleksandr-popov-9vDdkxSCAD4-unsplash.jpg?width=1200&height=900&mode=crop",
    },
  },
}